language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
mono:  
  - 5.10.0
dotnet: 2.0.0
os:  
  - linux
  - osx
osx_image: xcode7.1  
branches:  
  only:
    - master
    - /.*/
script:  
  - ./build.sh